image: docker:latest
services:
- docker:dind

stages:
- build
- release

variables:
  CONTAINER_BRANCH_IMAGE: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME
  CONTAINER_RELEASE_IMAGE: $CI_REGISTRY_IMAGE:latest
  CONTAINER_TAG_IMAGE: $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG
  IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME

before_script:
  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN registry.gitlab.com

build:
  stage: build
  script:
    - docker build --pull -t $CONTAINER_BRANCH_IMAGE .
    - docker push $CONTAINER_BRANCH_IMAGE
  only:
    - master
    - branches
    - tags

release-image:
    stage: release
    script:
        - docker pull $CONTAINER_BRANCH_IMAGE
        - docker tag $CONTAINER_BRANCH_IMAGE $CONTAINER_RELEASE_IMAGE
        - docker push $CONTAINER_RELEASE_IMAGE
    only:
        - master

release-tag:
    stage: release
    script:
        - docker pull $CONTAINER_BRANCH_IMAGE
        - docker tag $CONTAINER_BRANCH_IMAGE $CONTAINER_TAG_IMAGE
        - docker push $CONTAINER_TAG_IMAGE
    only:
        - tags

